services:
  - type: web
    name: pinn-cfd-surrogate
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapp.wsgi:application --bind 0.0.0.0:$PORT --workers 3
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_SETTINGS_MODULE
        value: "webapp.settings"
      - key: ALLOWED_HOSTS
        value: "pinn-and-cfd-surrogates.onrender.com,.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://pinn-and-cfd-surrogates.onrender.com,https://*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
